### ISSUE TITLE
WaffleIron Feature Generation - Missing Sequences

### ISSUE THREAD

**Issue by TillBeemelmanns** [astra-vision/PaSCo#10]
Hi,
thanks for this amazing work. 

I have a little problem generating the WaffleIron features. The feature generation only processes sequences 00 to 07. The remaining sequences are not generated, which then causes problem during PasCo training.  See image below.

![image](https://github.com/user-attachments/assets/fa1438df-4359-4717-ae12-f95437c504c2)

I am using this command to generate the features. 
```bash
python extract_point_features.py \
--path_dataset /workspace/data/SemanticKITTI \
--ckpt pretrained_models/WaffleIron-48-256__kitti/ckpt_last.pth \
--config configs/WaffleIron-48-256__kitti.yaml \
--result_folder /workspace/data/pasco_preprocess/kitti/waffleiron_v2 \
--phase val \
--num_workers 32 \
--num_votes 10 \
--batch_size 2
```

I was wondering if `--phase val` is correct. Shouldn't we use the train phase ?

Error that I get at training start:

```
111 M     Trainable params
0         Non-trainable params
111 M     Total params
444.202   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000000.pkl
/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000020.pkl
/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000010.pkl
/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000030.pkl
/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000050.pkl
/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000040.pkl
/workspace/data/pasco_preprocess/kitti/waffleiron_v2/sequences/08/seg_feats_tta/000060.pkl
Traceback (most recent call last):
  File "/workspace/scripts/train.py", line 248, in <module>
    main()
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/scripts/train.py", line 244, in main
    trainer.fit(model, data_module)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/pasco/data/semantic_kitti/kitti_dataset.py", line 138, in __getitem__
    items.append(self.get_individual(id))
  File "/workspace/pasco/data/semantic_kitti/kitti_dataset.py", line 150, in get_individual
    data = self.load_data_v3(sequence, frame_id, n_fuse_scans=self.n_fuse_scans)
  File "/workspace/pasco/data/semantic_kitti/kitti_dataset.py", line 370, in load_data_v3
    (xyz[:, 0] < self.max_extent[0])
UnboundLocalError: local variable 'xyz' referenced before assignment

root@rhea4:/workspace# 
```

Thanks,
Till

**Comment by anhquancao** [comment]
Hi @TillBeemelmanns,
Could you check if [this variable split](https://github.com/astra-vision/PaSCo/blob/main/WaffleIron_mod/datasets/semantic_kitti.py#L194) contains all the sequences?

**Comment by TillBeemelmanns** [comment]
Hmm all sequences are in the`split` list: ` [8, 0, 1, 2, 3, 4, 5, 6, 7, 9, 10]`.
I will try to run it again, just on 8, 9, 10 and let you know if that worked.

**Comment by TillBeemelmanns** [comment]
Oh, my fault. Was running out of disk space.

**Comment by the-king-of-yhq** [comment]
hello，why perform extract_point_feature to happen:
flatten = torch.sparse_coo_tensor(indices_non_zeros, weight_per_point, matrix_shape)
RuntimeError: size is inconsistent with indices: for dim 0, size is 5 but found index 31587840

**Comment by jmwang0117** [comment]
> hello，why perform extract_point_feature to happen: flatten = torch.sparse_coo_tensor(indices_non_zeros, weight_per_point, matrix_shape) RuntimeError: size is inconsistent with indices: for dim 0, size is 5 but found index 31587840

Did you solve this problem?
